### ISSUE TITLE
App hangs when scrolling article and then using 'next article'

### ISSUE THREAD

**Issue by bartlibert** [Ashinch/ReadYou#668]
**1. Environment**

-   Device: Pixel 7a
-   OS: Android 14
-   APP: 0.9.12

**2. Describe the bug**

The app occasionally hangs for me when I have scrolled in an article and then touch the "next article" button.
A quite consistent way to reproduce this for me is the following (but note that I also have this issue during "normal operation"):

1. Make sure you are in a list with a decent amount of articles
2. Open the first article
3. Quickly scroll through the article (does not have to go all the way down)
4. Click "next article"
5. Repeat the steps from step 3 until the app hangs

The toast will sometimes show "failed requirement" and sometimes "null"

Logcat when the issues happens:

```
03-27 11:03:32.975 28230 28303 D ProfileInstaller: Installing profile for me.ash.reader
03-27 11:03:53.207 28230 28230 E AndroidRuntime: Process: me.ash.reader, PID: 28230
03-27 11:03:57.009  1549  3179 D CoreBackPreview: startBackNavigation currentTask=Task{cd19d35 #40801 type=standard A=10311:me.ash.reader}, topRunningActivity=ActivityRecord{7c7536c u0 me.ash.reader/.infrastructure.android.MainActivity t40801}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@68fe293, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity}
03-27 11:03:57.059  1549  6003 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 5 from [5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server), [Gesture Monitor] swipe-up (server)]
03-27 11:03:57.203  1549  6003 W NotificationService: Toast already killed. pkg=me.ash.reader token=android.os.BinderProxy@8b29137
03-27 11:03:59.405  1549  2099 W InputDispatcher: Window 5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server) is unresponsive: 5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server) is not responding. Waited 5004ms for MotionEvent
03-27 11:03:59.406  1549  2099 W InputDispatcher: Canceling events for 5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server) because it is unresponsive
03-27 11:03:59.409  1549  2099 I WindowManager: ANR in Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity}. Reason:Input dispatching timed out (5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server) is not responding. Waited 5004ms for MotionEvent).
03-27 11:03:59.425 28230 28236 I me.ash.reader: Thread[5,tid=28236,WaitingInMainSignalCatcherLoop,Thread*=0xb400007a60d416f0,peer=0x12c00dc8,"Signal Catcher"]: reacting to signal 3
03-27 11:03:59.425 28230 28236 I me.ash.reader:
03-27 11:03:59.548 28230 28236 I me.ash.reader: Wrote stack traces to tombstoned
03-27 11:04:01.256  1549 28353 E ActivityManager: ANR in me.ash.reader (me.ash.reader/.infrastructure.android.MainActivity)
03-27 11:04:01.256  1549 28353 E ActivityManager: Reason: Input dispatching timed out (5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (server) is not responding. Waited 5004ms for MotionEvent).
03-27 11:04:01.256  1549 28353 E ActivityManager: Parent: me.ash.reader/.infrastructure.android.MainActivity
03-27 11:04:01.258  1549 28353 D ActivityManager: Completed ANR of me.ash.reader in 1844ms, latency 2ms
03-27 11:04:01.287  1549  1804 D CoreBackPreview: Window{101d15 u0 Application Not Responding: me.ash.reader}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@1929fef, mPriority=0, mIsAnimationCallback=false}
03-27 11:04:02.732  1549  1804 W ActivityTaskManager:   Force finishing activity me.ash.reader/.infrastructure.android.MainActivity
03-27 11:04:02.738  1549  1804 I ActivityManager: Killing 28230:me.ash.reader/u0a311 (adj 0): user request after error
03-27 11:04:02.739  1549  1804 D CoreBackPreview: Window{101d15 u0 Application Not Responding: me.ash.reader}: Setting back callback null
03-27 11:04:02.742  1549  1804 W InputManager-JNI: Input channel object '101d15 Application Not Responding: me.ash.reader (client)' was disposed without first being removed with the input manager!
03-27 11:04:02.839  1549  5475 I WindowManager: WIN DEATH: Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity}
03-27 11:04:02.840  1549  5475 W InputManager-JNI: Input channel object '5de75f6 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity (client)' was disposed without first being removed with the input manager!
03-27 11:04:02.840  1549  6014 I ImeTracker: me.ash.reader:9d3e7ec1: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_REMOVE_CLIENT
03-27 11:04:02.841  1549  6014 I ImeTracker: me.ash.reader:9d3e7ec1: onCancelled at PHASE_SERVER_SHOULD_HIDE
03-27 11:04:02.886  1549  1807 W WindowManager: Failed to deliver inset control state change to w=Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity EXITING}
03-27 11:04:02.911  1549  1803 V WindowManager:         {WCT{RemoteToken{f253da5 Task{cd19d35 #40801 type=standard A=10311:me.ash.reader}}} m=CLOSE f=NONE leash=Surface(name=Task=40801)/@0x18d0eb3 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},
03-27 11:04:02.943  1549  1807 W WindowManager: Failed to deliver inset control state change to w=Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity EXITING}
03-27 11:04:03.036  1549  5475 W WindowManager: Exception thrown during dispatchAppVisibility Window{5de75f6 u0 me.ash.reader/me.ash.reader.infrastructure.android.MainActivity EXITING}
03-27 11:04:03.233  1549  1806 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{7c7536c u0 me.ash.reader/.infrastructure.android.MainActivity t-1 f}}
```

**Comment by JunkFood02** [comment]
Should already get fixed in latest nightly builds or the upcoming v0.10.0 release

**Comment by bartlibert** [comment]
I tried the last nightly and I can still reproduce this unfortunately 🙁

**Comment by bartlibert** [comment]
I don't think so. A feed where I have the issue for example is https://www.nuus.be/feed/.
I have it both when using a local account, or via freshrss.
